### ISSUE TITLE
Decide how services publish metadata

### ISSUE THREAD

**Issue by jmandel** [cds-hooks/cds-hooks#10]
Current options include:

(I prefer (1), for being shorter and not overloaded with other FHIR data elements)
##### 1. via `$cds-hook-metadata` operation

   (e.g. payload [http://hooks.fhir.me:8081/cms-price-check/$cds-hook-metadata](http://hooks.fhir.me:8081/cms-price-check/$cds-hook-metadata))

``` json
{
   "resourceType":"Parameters",
   "parameter":[
      {
         "name":"name",
         "valueString":"CMS Pricing Service"
      },
      {
         "name":"description",
         "valueString":"Estimate the price of a prescription based on historical pharmacy dispensing data"
      },
      {
         "name":"activity",
         "valueCoding":{
            "system":"http://cds-hooks.smarthealthit.org/activity",
            "code":"medication-prescribe"
         }
      },
      {
         "name":"preFetchTemplate",
         "valueString":"Patient/{{Patient.id}}"
      }
   ]
}
```
#### 2. via FHIR Conformance statement

   (e.g. payload: http://hooks.fhir.me:8081/cms-price-check/metadata)

``` json
{
   "version":"1.0.2-7406-1.0.26",
   "acceptUnknown":"both",
   "description":"Mock CDS Services",
   "rest":[
      {
         "extension":[
            {
               "url":"http://fhir-registry.smarthealthit.org/StructureDefinition/cds-activity",
               "extension":[
                  {
                     "url":"name",
                     "valueString":"Check prices for a prescription in-progress"
                  },
                  {
                     "url":"activity",
                     "valueCoding":{
                        "code":"medication-prescribe",
                        "display":"Provide information about a prescription in-progress",
                        "system":"http://cds-hooks.smarthealthit.org/activity"
                     }
                  }
               ]
            }
         ],
         "mode":"server",
         "transactionMode":"both",
         "operation":[
            {
               "definition":{
                  "reference":"OperationDefinition/fso-cds-hook"
               },
               "name":"cds-hook"
            }
         ]
      }
   ],
   "resourceType":"Conformance",
   "status":"active",
   "date":"2016-01-09T15:39:51Z",
   "fhirVersion":"1.0.2-7406",
   "format":[
      "application/xml+fhir",
      "application/json+fhir"
   ],
   "id":"FhirServer",
   "name":"SMART FHIR Server Conformance Statement"
}
```

**Comment by kpshek** [comment]
@jmandel - I certainly am not a fan of trying to use the existing FHIR Conformance resource for this information so option 2 is my least preferred.

That leaves me with option 1. However, in your example above, it looks like a CDS Service is only able to communicate metadata on a particular activity (eg, medication-prescribe). I would think it would be preferable to communicate metadata about all activities offered up by the CDS Service.

So, I'll present another option, modified from my big [_Thoughts on CDS Hooks_ mailing list thread](https://groups.google.com/d/msg/cds-hooks/frHmx2VCvIE/TEWxUXLzEwAJ)) and to take into account the decision that we will use the [FHIR Parameters resource](https://www.hl7.org/fhir/parameters.html) (see #11):

#### 3. Via $cds-hooks-metadata operation for all hooks

Simplified view:
Request: GET /$cds-hooks-metadata

```
{
  hooks:              1..* {
    hook:             1..1 valueCoding,
    url:              1..1 valueUri,
    name:             1..1 valueString,
    description:      1..1 valueString,
    preFetchTemplate: 0..* valueString
  }
}
```

I'm lazy so I'm omitting the full response using Parameters (which would be the actual response).

Changes from option 1:
- Support a list of hooks rather than just one
- Pluralize the operations name ($cds-hook-metadata to $cds-hook**s**-metadata
- Specify the URL for each hook
- Rename activity to hook (pending #13)

**Comment by jmandel** [comment]
Thanks @kpshek! In the case where a single `$cds-hook` endpoint serves multiple different activities (medication-prescribe and patient-view, for example -- btw, see how using the word "hooks" there would have been akward?), I see the value in having a list of hooks.

But I'm not sure I understand the use case for giving each hook a separate URL. If these are independent services hosted by different parties, it would be strange to have a third-party publish the "metadata" for them all, and potentially give them different/misleading names, or incompatible `preFetchData` from what the hook publisher intended.

I like the idea of 1:1 correspondence between the publisher of a hook and the publisher of its metadata, which option (1) above achieves. We could tweak your proposal by dropping the `url`, and then the concern would resolve.

Now, maybe we do want to describe a role for meta-aggregation here (e.g. here's the "list of hooks I like to use", which points to external services). But that would be a different structure, I think -- just a simple list of metadata endpoints, rather than repeating all the details.

**Comment by kpshek** [comment]
> But I'm not sure I understand the use case for giving each hook a separate URL.

My thinking here is that I wouldn't want to implement some super endpoint whose first order of business is to do a switch statement on the activity/name (eg, patient-view, medication-prescribe) and delegate to the appropriate logic. If by some chance your patient-view and medication-prescribe services were nearly identical, you could simply give them the same URL if you really wanted. However, even in this case I'd still prefer them to have different URLs so that I can track metrics on each without examining the request.

> If these are independent services hosted by different parties, it would be strange to have a third-party publish the "metadata" for them all, and potentially give them different/misleading names, or incompatible preFetchData from what the hook publisher intended.
> I like the idea of 1:1 correspondence between the publisher of a hook and the publisher of its metadata, which option (1) above achieves. We could tweak your proposal by dropping the url, and then the concern would resolve.

You lost me here. I was assuming that the creator and company hosting a CDS Service would also host their metadata endpoint for their service so I agree with you on the 1:1 correspondence. Where did this idea of a third-party CDS Service aggregator come from?

**Comment by jmandel** [comment]
Top level question: If you agree that it's a good practice to keep the services separate, why not keep the Metadata separate too?

As for the aggregation issue: it's more a fear than an idea. Since there's no constraint, and "url" can be anything, an EHR consuming Metadata can get tricked/confused by a third party that badly tries to point to other services. Whereas if we adopted a stronger convention, this would be impossible.

**Comment by jmandel** [comment]
And never mind my "aggregation" use case: I was just trying to anticipate one (apparently non-)reason why you might have wanted to define multiple Hooks in the same Metadata file.

**Comment by kpshek** [comment]
> Top level question: If you agree that it's a good practice to keep the services separate, why not keep the Metadata separate too?

By separate, do you mean have a metadata endpoint for each service? If so, what I'd really love ([more discussion here](https://groups.google.com/forum/m/#!topic/cds-hooks/frHmx2VCvIE)) is:
- metadata: GET /:hook
- service: POST /:hook/:id

Eg:
- GET https://cds-provider/patient-view to read the metadata resource for this service
- POST https://cds-provider/patient-view/0aaafead-3788-4733-a0e8-6221b76cb477 to invoke an instance of this service

**But**, we're going with FHIR API conventions (Parameters, operations, etc) so I took that off the table mentally and am going with the `$` operation syntax. And, given that this doesn't resembles a RESTful API in this model, I don't know how to model what I want above in these constraints.

You have a lot more experience with FHIR modeling conventions than myself so if there is a way so if there is a better way, I'd love to know.

> Since there's no constraint, and "url" can be anything, an EHR consuming Metadata can get tricked/confused by a third party that badly tries to point to other services. Whereas if we adopted a stronger convention, this would be impossible.

I'm all for establishing stronger conventions; I want this too and would prefer if CDS Providers weren't allowed to specify arbitrary URLs. This is another thing I like above the URI design that I would love -- CDS Providers just need to register their base URL with the EHR / registry.

I get why you've got the service defined at that master endpoint. Using the [FHIR operations framework](https://www.hl7.org/fhir/operations.html) doesn't provide much flexibility (in the current FHIR spec). You'd have to define something like $cds-service-patient-view, $cds-service-medication-prescribe, etc. I'll reiterate that I think it's important that these services are offered at distinct URIs -- not just for the maintainability/clarity of the service code but also for monitoring, metrics, and independent scalability that distinct URIs would offer.

**Comment by kpshek** [comment]
To close the loop on this, @jmandel & I came up with a [discovery API documented here](http://cds-hooks.org/#discovery)
